version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
    steps:
      - run:
          name: Install dependencies
          command: |
            apt update && apt -y install pyqt5-dev-tools python3-pyqt5 pip3
            pip3 install pyinstaller
      - checkout
      - run:
          name: Build files
          command: make
      - run:
          name: Build binary
          command: pyinstaller --onefile correlation_points.py
      - store_artifacts:
          path: dist/correlation_points
