version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Install dependencies
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update && apt-get -y install pyqt5-dev-tools python3-pyqt5 python3-pip python3-opencv
            pip3 install pyinstaller
      - checkout
      - run:
          name: Build files
          command: make
      - run:
          name: Build binary
          command: pyinstaller --onefile correlation_points.py
      - store_artifacts:
          path: dist/correlation_points
