version: 2
jobs:
  ubuntu:
    docker:
      - image: ubuntu:18.04
    steps:
      - run:
          name: Install dependencies
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update && apt-get -y install pyqt5-dev-tools python3-pyqt5 python3-pip python3-opencv
            pip3 install pyinstaller
      - checkout
      - run:
          name: Build files
          command: make
      - run:
          name: Build binary
          command: pyinstaller --onefile --distpath dist-linux correlation_points.py
      - store_artifacts:
          path: dist-linux/correlation_points

  windows:
    docker:
      - image: cdrx/pyinstaller-windows
    steps:
      - run:
          name: Install dependencies
          command: |
            apt-get update && apt-get -y install make
            pip install pyqt5
      - run:
          name: Build binary
          command: |
            make
            pyinstaller --onefile --distpath dist-windows correlation_points.py
      - store_artifacts:
          path: dist-windows/corelation_points.exe

workflows:
  version: 2
  build:
    jobs:
      - ubuntu
      - windows
